// Code generated by "stringer -type state"; DO NOT EDIT.

package libjson

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Start-0]
	_ = x[InObject-1]
	_ = x[EndObject-2]
	_ = x[InArray-3]
	_ = x[EndArray-4]
	_ = x[String-5]
	_ = x[Number-6]
	_ = x[Atom-7]
}

const _state_name = "StartInObjectEndObjectInArrayEndArrayStringNumberAtom"

var _state_index = [...]uint8{0, 5, 13, 22, 29, 37, 43, 49, 53}

func (i state) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_state_index)-1 {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[idx]:_state_index[idx+1]]
}
